spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/data;AUTO_SERVER=TRUE
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database: h2
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
